# Generated by Django 5.0.1 on 2026-04-19 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='活动名称')),
                ('type', models.CharField(max_length=50, verbose_name='活动类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('start_date', models.DateTimeField(verbose_name='开始时间')),
                ('end_date', models.DateTimeField(verbose_name='结束时间')),
                ('client', models.CharField(blank=True, max_length=255, verbose_name='客户')),
                ('client_contact', models.CharField(blank=True, max_length=100, verbose_name='客户联系人')),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预估预算')),
                ('actual_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际预算')),
                ('budget_variance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预算偏差')),
                ('status', models.CharField(choices=[('planning', '策划中'), ('executing', '执行中'), ('completed', '已完成'), ('reviewed', '已复盘'), ('cancelled', '已取消')], default='planning', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_events', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, verbose_name='预算科目')),
                ('name', models.CharField(max_length=255, verbose_name='预算项名称')),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预估金额')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际金额')),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='偏差')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='events.event', verbose_name='活动')),
            ],
            options={
                'verbose_name': '预算明细',
                'verbose_name_plural': '预算明细',
                'db_table': 'budget_items',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_status_8890b6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date'], name='events_start_d_6c01fc_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['owner'], name='events_owner_i_97f353_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-created_at'], name='events_created_fc135f_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['event'], name='budget_item_event_i_4ef045_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['status'], name='budget_item_status_0bae9a_idx'),
        ),
    ]
