# Generated by Django 5.0.1 on 2026-04-19 15:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('planner', '策划师'), ('executor', '执行师'), ('designer', '设计师'), ('coordinator', '协调员'), ('observer', '观察员')], default='executor', max_length=20, verbose_name='角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '活动参与者',
                'verbose_name_plural': '活动参与者',
                'db_table': 'event_participants',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_events', through='events.EventParticipant', to=settings.AUTH_USER_MODEL, verbose_name='参与者'),
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('category', models.CharField(choices=[('conference', '会议'), ('exhibition', '展会'), ('performance', '演出'), ('party', '派对'), ('training', '培训'), ('other', '其他')], max_length=20, verbose_name='分类')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('default_duration_days', models.PositiveIntegerField(default=3, verbose_name='默认持续时间(天)')),
                ('default_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='默认预算')),
                ('task_templates', models.JSONField(default=list, verbose_name='任务模板')),
                ('budget_templates', models.JSONField(default=list, verbose_name='预算模板')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '活动模板',
                'verbose_name_plural': '活动模板',
                'db_table': 'event_templates',
            },
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['event', 'user'], name='event_parti_event_i_fdf78f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['role'], name='event_parti_role_29cea7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='eventtemplate',
            index=models.Index(fields=['category'], name='event_templ_categor_6ed874_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtemplate',
            index=models.Index(fields=['is_active'], name='event_templ_is_acti_571150_idx'),
        ),
    ]
