# Generated by Django 5.0.1 on 2026-04-20 17:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_type', models.CharField(choices=[('client', '客户'), ('supplier', '供应商'), ('partner', '合作伙伴')], max_length=20, verbose_name='档案类型')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司名称')),
                ('legal_person', models.CharField(blank=True, max_length=100, verbose_name='法人代表')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name='注册号')),
                ('contact_info', models.JSONField(default=dict, verbose_name='联系信息')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='行业')),
                ('business_scope', models.TextField(blank=True, verbose_name='业务范围')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '非活跃'), ('blacklisted', '黑名单'), ('prospective', '潜在'), ('archived', '已归档')], default='prospective', max_length=20, verbose_name='状态')),
                ('credit_score', models.IntegerField(default=0, help_text='0-100分', verbose_name='信用评分')),
                ('quality_score', models.IntegerField(default=0, help_text='0-100分', verbose_name='质量评分')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='medium', max_length=20, verbose_name='风险等级')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_contact_date', models.DateTimeField(blank=True, null=True, verbose_name='最后联系时间')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_profiles', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_profiles', to=settings.AUTH_USER_MODEL, verbose_name='档案所有者')),
            ],
            options={
                'verbose_name': '关联方档案',
                'verbose_name_plural': '关联方档案',
                'db_table': 'contact_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('position', models.CharField(blank=True, choices=[('ceo', 'CEO/总经理'), ('director', '总监'), ('manager', '经理'), ('coordinator', '协调员'), ('sales', '销售'), ('technical', '技术'), ('finance', '财务'), ('other', '其他')], max_length=20, verbose_name='职位')),
                ('position_other', models.CharField(blank=True, max_length=100, verbose_name='其他职位')),
                ('contact_info', models.JSONField(default=dict, verbose_name='联系方式')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要联系人')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='profiles.contactprofile', verbose_name='所属档案')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
                'db_table': 'contact_persons',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InteractionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('event', '活动合作'), ('contract', '合同签署'), ('communication', '沟通联系'), ('meeting', '会议交流'), ('payment', '支付交易'), ('support', '技术支持'), ('complaint', '投诉处理'), ('negotiation', '商务谈判'), ('other', '其他')], max_length=20, verbose_name='交互类型')),
                ('title', models.CharField(max_length=255, verbose_name='交互标题')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('related_event_id', models.UUIDField(blank=True, null=True, verbose_name='相关活动ID')),
                ('related_project_id', models.CharField(blank=True, max_length=100, verbose_name='相关项目编号')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('satisfaction_score', models.IntegerField(blank=True, help_text='1-5分', null=True, verbose_name='满意度评分')),
                ('outcome_status', models.CharField(blank=True, max_length=50, verbose_name='结果状态')),
                ('interaction_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='交互时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interactions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='profiles.contactprofile', verbose_name='关联档案')),
            ],
            options={
                'verbose_name': '交互历史',
                'verbose_name_plural': '交互历史',
                'db_table': 'interaction_histories',
                'ordering': ['-interaction_date'],
            },
        ),
        migrations.CreateModel(
            name='ProfileEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluation_date', models.DateTimeField(auto_now_add=True, verbose_name='评估时间')),
                ('credit_score', models.IntegerField(blank=True, help_text='0-100分', null=True, verbose_name='信用评分')),
                ('quality_score', models.IntegerField(blank=True, help_text='0-100分', null=True, verbose_name='质量评分')),
                ('service_quality', models.IntegerField(blank=True, help_text='1-5分', null=True, verbose_name='服务质量')),
                ('response_speed', models.IntegerField(blank=True, help_text='1-5分', null=True, verbose_name='响应速度')),
                ('professional_ability', models.IntegerField(blank=True, help_text='1-5分', null=True, verbose_name='专业能力')),
                ('evaluation_criteria', models.JSONField(default=dict, verbose_name='评估标准')),
                ('risk_assessment', models.TextField(blank=True, verbose_name='风险评估')),
                ('risk_level', models.CharField(blank=True, choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], max_length=20, verbose_name='风险等级')),
                ('recommendations', models.TextField(verbose_name='建议和意见')),
                ('overall_conclusion', models.CharField(blank=True, max_length=500, verbose_name='总体结论')),
                ('next_evaluation_date', models.DateTimeField(blank=True, null=True, verbose_name='下次评估时间')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='评估人')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='profiles.contactprofile', verbose_name='评估档案')),
            ],
            options={
                'verbose_name': '档案评估',
                'verbose_name_plural': '档案评估',
                'db_table': 'profile_evaluations',
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.AddIndex(
            model_name='contactprofile',
            index=models.Index(fields=['profile_type'], name='contact_pro_profile_ff827c_idx'),
        ),
        migrations.AddIndex(
            model_name='contactprofile',
            index=models.Index(fields=['status'], name='contact_pro_status_54c8bf_idx'),
        ),
        migrations.AddIndex(
            model_name='contactprofile',
            index=models.Index(fields=['credit_score'], name='contact_pro_credit__f7899e_idx'),
        ),
        migrations.AddIndex(
            model_name='contactprofile',
            index=models.Index(fields=['quality_score'], name='contact_pro_quality_1b30dc_idx'),
        ),
        migrations.AddIndex(
            model_name='contactprofile',
            index=models.Index(fields=['created_at'], name='contact_pro_created_99909e_idx'),
        ),
        migrations.AddIndex(
            model_name='contactprofile',
            index=models.Index(fields=['deleted_at'], name='contact_pro_deleted_c25fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='contactperson',
            index=models.Index(fields=['profile'], name='contact_per_profile_7e917f_idx'),
        ),
        migrations.AddIndex(
            model_name='contactperson',
            index=models.Index(fields=['is_primary'], name='contact_per_is_prim_dd15f5_idx'),
        ),
        migrations.AddIndex(
            model_name='contactperson',
            index=models.Index(fields=['is_active'], name='contact_per_is_acti_357a67_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionhistory',
            index=models.Index(fields=['profile'], name='interaction_profile_7ae7e8_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionhistory',
            index=models.Index(fields=['interaction_type'], name='interaction_interac_4707f9_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionhistory',
            index=models.Index(fields=['interaction_date'], name='interaction_interac_c88b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='profileevaluation',
            index=models.Index(fields=['profile'], name='profile_eva_profile_99f78b_idx'),
        ),
        migrations.AddIndex(
            model_name='profileevaluation',
            index=models.Index(fields=['evaluation_date'], name='profile_eva_evaluat_963a33_idx'),
        ),
        migrations.AddIndex(
            model_name='profileevaluation',
            index=models.Index(fields=['evaluator'], name='profile_eva_evaluat_92be5e_idx'),
        ),
    ]
