# Generated by Django 5.0.1 on 2026-04-19 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('task_type', models.CharField(choices=[('planning', '策划'), ('guest', '嘉宾'), ('material', '物料'), ('venue', '场地'), ('promotion', '宣传'), ('onsite', '现场'), ('review', '复盘')], max_length=20, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '待办'), ('ready', '就绪'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消'), ('blocked', '阻塞')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='进度(%)')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止日期')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='开始日期')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='events.event', verbose_name='活动')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='CommunicationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='沟通内容')),
                ('requirements', models.TextField(blank=True, verbose_name='要求')),
                ('communicators', models.JSONField(default=list, verbose_name='联系人')),
                ('conclusion_files', models.JSONField(default=list, verbose_name='结论文件')),
                ('is_closed', models.BooleanField(default=False, verbose_name='已闭环')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication', to='tasks.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '沟通任务',
                'verbose_name_plural': '沟通任务',
                'db_table': 'communication_tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='tasks.task', verbose_name='依赖任务')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='tasks.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务依赖',
                'verbose_name_plural': '任务依赖',
                'db_table': 'task_dependencies',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['event'], name='tasks_event_i_67e148_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_status_031d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_type'], name='tasks_task_ty_7bc323_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee'], name='tasks_assigne_462a05_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='tasks_due_dat_0359a9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-created_at'], name='tasks_created_d28591_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdependency',
            index=models.Index(fields=['task'], name='task_depend_task_id_52f414_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdependency',
            index=models.Index(fields=['depends_on'], name='task_depend_depends_af5f16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('task', 'depends_on')},
        ),
    ]
