# Generated by Django 5.0.1 on 2026-04-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationtask',
            name='communicators',
            field=models.JSONField(blank=True, default=list, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='communicationtask',
            name='conclusion_files',
            field=models.JSONField(blank=True, default=list, verbose_name='结论文件'),
        ),
    ]
