# Generated by Django 5.0.1 on 2026-04-19 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('event_types', models.JSONField(default=list, verbose_name='适用活动类型')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '核验清单模板',
                'verbose_name_plural': '核验清单模板',
                'db_table': 'checklist_templates',
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('required', models.BooleanField(default=True, verbose_name='必填')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '核验清单项模板',
                'verbose_name_plural': '核验清单项模板',
                'db_table': 'checklist_item_templates',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='实例名称')),
                ('status', models.CharField(default='incomplete', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='events.event', verbose_name='活动')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checklists.checklisttemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '核验清单实例',
                'verbose_name_plural': '核验清单实例',
                'db_table': 'checklist_instances',
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('attachments', models.JSONField(default=list, verbose_name='附件')),
                ('status', models.CharField(choices=[('pending', '待检查'), ('in_progress', '检查中'), ('passed', '通过'), ('failed', '未通过'), ('skipped', '跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='检查时间')),
                ('location', models.JSONField(blank=True, null=True, verbose_name='位置(GPS)')),
                ('offline_pending', models.BooleanField(default=False, verbose_name='待同步')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='检查人')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklistinstance', verbose_name='清单实例')),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checklists.checklistitemtemplate', verbose_name='模板项')),
            ],
            options={
                'verbose_name': '核验清单项',
                'verbose_name_plural': '核验清单项',
                'db_table': 'checklist_items',
                'indexes': [models.Index(fields=['instance'], name='checklist_i_instanc_a79472_idx'), models.Index(fields=['status'], name='checklist_i_status_fbdc84_idx'), models.Index(fields=['offline_pending'], name='checklist_i_offline_96739c_idx')],
            },
        ),
    ]
