# Generated by Django 5.0.1 on 2026-04-19 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
        ('events', '0002_eventparticipant_event_participants_eventtemplate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistinstance',
            options={'ordering': ['-created_at'], 'verbose_name': '核验清单实例', 'verbose_name_plural': '核验清单实例'},
        ),
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['order'], 'verbose_name': '核验清单项', 'verbose_name_plural': '核验清单项'},
        ),
        migrations.AlterModelOptions(
            name='checklisttemplate',
            options={'ordering': ['-updated_at'], 'verbose_name': '核验清单模板', 'verbose_name_plural': '核验清单模板'},
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='completion_rate',
            field=models.FloatField(default=0.0, verbose_name='完成度'),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='metadata',
            field=models.JSONField(default=dict, verbose_name='元数据'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='metadata',
            field=models.JSONField(default=dict, verbose_name='元数据'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='required',
            field=models.BooleanField(default=True, verbose_name='必填'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='权重'),
        ),
        migrations.AddField(
            model_name='checklistitemtemplate',
            name='metadata',
            field=models.JSONField(default=dict, verbose_name='元数据'),
        ),
        migrations.AddField(
            model_name='checklistitemtemplate',
            name='status',
            field=models.CharField(default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='checklistitemtemplate',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='权重'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='checklist_type',
            field=models.CharField(default='custom', max_length=50, verbose_name='清单类型'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='metadata',
            field=models.JSONField(default=dict, verbose_name='元数据'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='status',
            field=models.CharField(default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='tags',
            field=models.JSONField(default=list, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='version',
            field=models.CharField(default='1.0.0', max_length=50, verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='template_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='checklists.checklistitemtemplate', verbose_name='模板项'),
        ),
        migrations.AddIndex(
            model_name='checklistinstance',
            index=models.Index(fields=['event'], name='checklist_i_event_i_9c3a74_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistinstance',
            index=models.Index(fields=['template'], name='checklist_i_templat_ccb54a_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistinstance',
            index=models.Index(fields=['status'], name='checklist_i_status_6f3b0d_idx'),
        ),
    ]
