# Generated by Django 5.0.1 on 2026-04-29 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_checklist_advanced_features'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='checklistexport',
            new_name='checklist_e_instanc_967284_idx',
            old_name='idx_export_instance',
        ),
        migrations.RenameIndex(
            model_name='checklistexport',
            new_name='checklist_e_templat_e715d6_idx',
            old_name='idx_export_template',
        ),
        migrations.RenameIndex(
            model_name='checklistexport',
            new_name='checklist_e_status_c924d3_idx',
            old_name='idx_export_status',
        ),
        migrations.RenameIndex(
            model_name='checklistexport',
            new_name='checklist_e_export__fa3f5f_idx',
            old_name='idx_export_format',
        ),
        migrations.RenameIndex(
            model_name='checklistimport',
            new_name='checklist_i_status_48b6f2_idx',
            old_name='idx_import_status',
        ),
        migrations.RenameIndex(
            model_name='checklistimport',
            new_name='checklist_i_import__14df58_idx',
            old_name='idx_import_format',
        ),
        migrations.RenameIndex(
            model_name='checklistverification',
            new_name='checklist_v_instanc_aebc71_idx',
            old_name='idx_verification_instance',
        ),
        migrations.RenameIndex(
            model_name='checklistverification',
            new_name='checklist_v_status_7e4ec6_idx',
            old_name='idx_verification_status',
        ),
        migrations.RenameIndex(
            model_name='checklistverification',
            new_name='checklist_v_approva_2a0a3d_idx',
            old_name='idx_verification_approval',
        ),
        migrations.RenameIndex(
            model_name='checklistverification',
            new_name='checklist_v_verifie_c92e69_idx',
            old_name='idx_verification_verifier',
        ),
        migrations.RenameIndex(
            model_name='checklistverification',
            new_name='checklist_v_require_aacd5a_idx',
            old_name='idx_verification_requires_approval',
        ),
        migrations.RenameIndex(
            model_name='checklistverificationdetail',
            new_name='checklist_v_verific_bf89c9_idx',
            old_name='idx_verification_detail_verification',
        ),
        migrations.RenameIndex(
            model_name='checklistverificationdetail',
            new_name='checklist_v_checkli_9bcda1_idx',
            old_name='idx_verification_detail_item',
        ),
        migrations.RenameIndex(
            model_name='checklistverificationdetail',
            new_name='checklist_v_status_f03dc6_idx',
            old_name='idx_verification_detail_status',
        ),
        migrations.RenameIndex(
            model_name='checklistverificationexception',
            new_name='checklist_v_verific_349f01_idx',
            old_name='idx_verification_exception_verification',
        ),
        migrations.RenameIndex(
            model_name='checklistverificationexception',
            new_name='checklist_v_status_cc39f5_idx',
            old_name='idx_verification_exception_status',
        ),
        migrations.RenameIndex(
            model_name='checklistverificationexception',
            new_name='checklist_v_excepti_7de3ae_idx',
            old_name='idx_verification_exception_type',
        ),
        migrations.RenameIndex(
            model_name='checklistverificationexception',
            new_name='checklist_v_assigne_da0ef1_idx',
            old_name='idx_verification_exception_assigned',
        ),
        migrations.RenameIndex(
            model_name='checklistversion',
            new_name='checklist_v_templat_30ef9d_idx',
            old_name='idx_version_template',
        ),
        migrations.RenameIndex(
            model_name='checklistversion',
            new_name='checklist_v_instanc_39afa6_idx',
            old_name='idx_version_instance',
        ),
        migrations.RenameIndex(
            model_name='checklistversion',
            new_name='checklist_v_version_68986b_idx',
            old_name='idx_version_number',
        ),
        migrations.RenameIndex(
            model_name='checklistversion',
            new_name='checklist_v_is_acti_a1be2f_idx',
            old_name='idx_version_active',
        ),
        migrations.AlterField(
            model_name='checklistexport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checklistimport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checklistverification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checklistverificationdetail',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checklistverificationexception',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checklistversion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checklistversioncomparison',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
