# Generated by Django 5.0.1 on 2026-04-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('issue', '问题'), ('experience', '经验'), ('best_practice', '最佳实践')], max_length=20, verbose_name='条目类型')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='分类')),
                ('related_events', models.JSONField(default=list, verbose_name='关联活动')),
                ('related_tasks', models.JSONField(default=list, verbose_name='关联任务')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否验证')),
                ('popularity', models.PositiveIntegerField(default=0, verbose_name='流行度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '知识条目',
                'verbose_name_plural': '知识条目',
                'db_table': 'knowledge_entries',
            },
        ),
    ]
