# Generated by Django 5.0.1 on 2026-04-29 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='knowledgeentry',
            index=models.Index(fields=['entry_type'], name='knowledge_e_entry_t_efde49_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeentry',
            index=models.Index(fields=['-created_at'], name='knowledge_e_created_2c82be_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeentry',
            index=models.Index(fields=['-popularity'], name='knowledge_e_popular_901eef_idx'),
        ),
    ]
