# Generated by Django 5.0.1 on 2026-04-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_deleted_at_user_deleted_by_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='user_agent',
            field=models.TextField(blank=True, default='', verbose_name='用户代理'),
        ),
    ]
