# Generated by Django 5.0.1 on 2026-04-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='复盘标题')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('in_progress', '进行中'), ('completed', '已完成')], default='draft', max_length=20, verbose_name='状态')),
                ('goal_achievement', models.TextField(blank=True, verbose_name='目标达成')),
                ('process_execution', models.TextField(blank=True, verbose_name='流程执行')),
                ('cost_control', models.TextField(blank=True, verbose_name='成本控制')),
                ('customer_feedback', models.TextField(blank=True, verbose_name='客户反馈')),
                ('team_collaboration', models.TextField(blank=True, verbose_name='团队协作')),
                ('successes', models.TextField(blank=True, verbose_name='成功经验')),
                ('improvements', models.TextField(blank=True, verbose_name='待改进项')),
                ('action_items', models.TextField(blank=True, verbose_name='行动项')),
                ('related_issues', models.JSONField(default=list, verbose_name='相关问题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='events.event', verbose_name='活动')),
            ],
            options={
                'verbose_name': '复盘',
                'verbose_name_plural': '复盘',
                'db_table': 'reviews',
            },
        ),
    ]
