# Generated by Django 5.0.1 on 2026-05-04 13:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fileauditlog',
            name='files_audit_file_me_c97ea7_idx',
        ),
        migrations.RemoveIndex(
            model_name='fileauditlog',
            name='files_audit_perform_73b135_idx',
        ),
        migrations.RemoveIndex(
            model_name='fileauditlog',
            name='files_audit_action_7bc05f_idx',
        ),
        migrations.RemoveIndex(
            model_name='fileauditlog',
            name='files_audit_perform_14527c_idx',
        ),
        migrations.RemoveIndex(
            model_name='filemetadata',
            name='files_metad_file_id_6b8a86_idx',
        ),
        migrations.RemoveIndex(
            model_name='filemetadata',
            name='files_metad_uploade_5e53a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='filemetadata',
            name='files_metad_owner_i_a85a02_idx',
        ),
        migrations.RemoveIndex(
            model_name='filemetadata',
            name='files_metad_status_d19b9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='filemetadata',
            name='files_metad_file_ca_a6b318_idx',
        ),
        migrations.RemoveIndex(
            model_name='filepreviewcache',
            name='files_previ_cache_k_d3281b_idx',
        ),
        migrations.RemoveIndex(
            model_name='filepreviewcache',
            name='files_previ_file_me_40c2fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='filepreviewcache',
            name='files_previ_expires_e55e54_idx',
        ),
        migrations.RemoveIndex(
            model_name='fileshare',
            name='files_share_share_i_9d2694_idx',
        ),
        migrations.RemoveIndex(
            model_name='fileshare',
            name='files_share_file_me_b41d8c_idx',
        ),
        migrations.RemoveIndex(
            model_name='fileshare',
            name='files_share_created_fcd1c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='fileversion',
            name='files_versi_version_f2da6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='fileversion',
            name='files_versi_file_me_d0d150_idx',
        ),
        migrations.RemoveIndex(
            model_name='fileversion',
            name='files_versi_version_5701ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='presignedurl',
            name='files_presi_url_id_27a630_idx',
        ),
        migrations.RemoveIndex(
            model_name='presignedurl',
            name='files_presi_request_91b88e_idx',
        ),
        migrations.RemoveIndex(
            model_name='presignedurl',
            name='files_presi_status_625597_idx',
        ),
        migrations.RemoveIndex(
            model_name='presignedurl',
            name='files_presi_expires_241c7c_idx',
        ),
        migrations.AlterField(
            model_name='fileauditlog',
            name='action',
            field=models.CharField(choices=[('upload', '上传'), ('download', '下载'), ('delete', '删除'), ('share', '分享'), ('view', '查看'), ('edit', '编辑'), ('move', '移动'), ('copy', '复制'), ('restore', '恢复'), ('quarantine', '隔离'), ('scan', '扫描')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='fileauditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='checksum',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='etag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='file_category',
            field=models.CharField(choices=[('document', '文档'), ('image', '图片'), ('video', '视频'), ('audio', '音频'), ('archive', '压缩包'), ('other', '其他')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='file_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='status',
            field=models.CharField(choices=[('uploading', '上传中'), ('processing', '处理中'), ('completed', '完成'), ('failed', '失败'), ('deleted', '已删除'), ('quarantine', '隔离')], db_index=True, default='uploading', max_length=20),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='presignedurl',
            name='status',
            field=models.CharField(choices=[('active', '活跃'), ('used', '已使用'), ('expired', '已过期'), ('cancelled', '已取消'), ('failed', '失败')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignedurl',
            name='url_type',
            field=models.CharField(choices=[('upload', '上传'), ('download', '下载'), ('preview', '预览')], db_index=True, max_length=20),
        ),
    ]
