# Generated by Django 5.0.1 on 2026-05-02 05:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('success', '成功')], db_index=True, default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(db_index=True, help_text='通知来源系统模块', max_length=50)),
                ('related_object_type', models.CharField(blank=True, help_text='关联对象类型（Event, Task等）', max_length=100)),
                ('related_object_id', models.CharField(blank=True, db_index=True, help_text='关联对象ID', max_length=100)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['read', 'created_at'], name='notificatio_read_52ee31_idx'), models.Index(fields=['source', '-created_at'], name='notificatio_source_4e88cd_idx')],
            },
        ),
    ]
